CREATE TABLE players
(
    PLAYER_NAME TEXT CHECK(PLAYER_NAME != ''), 
    TEAM_ID INTEGER CHECK(TEAM_ID > 0),
    PLAYER_ID INTEGER CHECK(PLAYER_ID > 0) PRIMARY KEY
);

CREATE TABLE games
(
	GAME_DATE_EST DATE,
	GAME_ID INTEGER UNIQUE CHECK(GAME_ID > 0) PRIMARY KEY,
	GAME_STATUS_TEXT TEXT,
	HOME_TEAM_ID INTEGER CHECK (HOME_TEAM_ID > 0),
	VISITOR_TEAM_ID INTEGER CHECK (VISITOR_TEAM_ID > 0),
	SEASON SMALLINT CHECK(SEASON <= 2019),
	TEAM_ID_home INTEGER CHECK (TEAM_ID_home > 0),
	PTS_home NUMERIC,
	FG_PCT_home NUMERIC,
	FT_PCT_home NUMERIC,
	FG3_PCT_home NUMERIC,
	AST_home NUMERIC,
	REB_home NUMERIC, 
	TEAM_ID_away INTEGER,
	PTS_away NUMERIC,
	FG_PCT_away NUMERIC,
	FT_PCT_away NUMERIC,
	FG3_PCT_away NUMERIC, 
	AST_away NUMERIC,
	REB_away NUMERIC,
	HOME_TEAM_WINS SMALLINT
);

CREATE TABLE teams
(
	LEAGUE_ID INTEGER,
	TEAM_ID INTEGER PRIMARY KEY,
	MIN_YEAR SMALLINT,
	MAX_YEAR SMALLINT,
	ABBREVIATION TEXT,
	NICKNAME TEXT,
	YEARFOUNDED INTEGER,
	CITY TEXT,
	ARENA TEXT,
	ARENACAPACITY INTEGER,
	COM_OWNER TEXT,
	GENERALMANAGER TEXT,
	HEADCOACH TEXT,
	DLEAGUEAFFILIATION TEXT
);

CREATE TABLE games_details
(
	GAME_ID INTEGER,
	TEAM_ID INTEGER,
	TEAM_ABBREVIATION TEXT,
	TEAM_CITY TEXT,
	PLAYER_ID INTEGER,
	PLAYER_NAME TEXT,
	START_POSITION TEXT,
	COMMENT_T TEXT,
	MIN_TIME TEXT,
	FGM NUMERIC,
	FGA NUMERIC,
	FG_PCT NUMERIC,
	FG3M NUMERIC,
	FG3A NUMERIC,
	FG3_PCT NUMERIC,
	FTM NUMERIC,
	FTA NUMERIC,
	FT_PCT NUMERIC,
	OREB NUMERIC,
	DREB NUMERIC,
	REB NUMERIC,
	AST NUMERIC,
	STL NUMERIC,
	BLK NUMERIC,
	T_NUM NUMERIC,
	PF NUMERIC,
	PTS NUMERIC,
	PLUS_MINUS NUMERIC,

	FOREIGN KEY (GAME_ID) REFERENCES games(GAME_ID),
	FOREIGN KEY (TEAM_ID) REFERENCES teams(TEAM_ID),
	FOREIGN KEY (PLAYER_ID) REFERENCES players(PLAYER_ID)
);

CREATE TABLE ranking
(
	TEAM_ID INTEGER,
	LEAGUE_ID INTEGER,
	SEASON_ID INTEGER,
	STANDINGSDATE DATE,
	CONFERENCE TEXT,
	TEAM TEXT,
	G_I SMALLINT,
	W SMALLINT,
	L SMALLINT,
	W_PCT NUMERIC,
	HOME_RECORD TEXT,
	ROAD_RECORD TEXT,
	FOREIGN KEY (TEAM_ID) REFERENCES teams(TEAM_ID)
);

copy players(PLAYER_NAME,TEAM_ID,PLAYER_ID) from '/home/lyubaxapro/database/lab1/players.csv' with delimiter ',' header csv;

copy games(GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,
	FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,
	AST_away,REB_away,HOME_TEAM_WINS) from '/home/lyubaxapro/database/lab1/games.csv' with delimiter ',' header csv;
	
copy teams(LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,COM_OWNER,GENERALMANAGER,
	HEADCOACH,DLEAGUEAFFILIATION) from '/home/lyubaxapro/database/lab1/teams.csv' with delimiter ',' header csv;

copy games_details(GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,
	START_POSITION,COMMENT_T,MIN_TIME,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,T_NUM,PF,PTS,
	PLUS_MINUS) from '/home/lyubaxapro/database/lab1/games_details.csv' with delimiter ',' header csv;

copy ranking(TEAM_ID,LEAGUE_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G_I,W,L,W_PCT,HOME_RECORD,
	ROAD_RECORD) from '/home/lyubaxapro/database/lab1/ranking.csv' with delimiter ',' header csv;
	